resources:
  pipelines:
    - pipeline: build
      source: 'Build and Test'
      trigger: 
        branches:
          include:
            - main

trigger: none

jobs:
  - job: deploy
    displayName: 'Deploy to Azure'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - download: build
        artifact: drop
        displayName: 'Download build artifact'
        patterns: '**/*'

      - task: AzureStaticWebApp@0
        inputs:
          app_location: '.'
          output_location: '$(Pipeline.Workspace)/drop'
          skip_app_build: true
          skip_api_build: true
          is_static_export: true
          azure_static_web_apps_api_token: $(deployment_token)
        displayName: 'Deploy to Azure Static Web Apps'
