resources:
  pipelines:
    - pipeline: build
      source: 'Build and Test'
      trigger:
        branches:
          include:
            - main

trigger: none

jobs:
  - job: deploy
    displayName: 'Deploy to Azure'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - download: build
        artifact: drop
        displayName: 'Download build artifact'
        patterns: '**/*'

      - task: AzureCLI@2
        displayName: 'Deploy to Azure Static Web Apps using az cli'
        inputs:
          azureSubscription: 'azure-service-connection'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account set --subscription b7ecff0e-62e0-44cd-8091-228d1894ed1f
            az staticwebapp upload `
              --name testswa `
              --resource-group cicd `
              --source "$(Pipeline.Workspace)/drop"
